### ISSUE TITLE
'make install' doesn't install bin/reseq

### ISSUE THREAD

**Issue by bryank-cs** [schmeing/ReSequenceR#1]
The reseq/CMakeLists.txt file is missing an install() directive, so the actual executable never gets installed. Adding this seemed to work:
```
--- reseq/CMakeLists.txt.orig   2019-10-23 16:42:08.000000000 -0400
+++ reseq/CMakeLists.txt        2019-10-23 16:41:48.000000000 -0400
@@ -20,3 +20,7 @@
 target_link_libraries(reseq ${SEQAN_LIBRARIES})
 target_link_libraries(reseq ${Boost_LIBRARIES})
 target_compile_options(reseq PRIVATE ${PRIVATE_COMPILE_OPTIONS})
+install(TARGETS reseq DataStatsInterface DataStats
+    RUNTIME DESTINATION bin
+    LIBRARY DESTINATION lib
+    ARCHIVE DESTINATION lib/static)
```

Also, in the top level CMakeLists.txt file, I don't think this is valid:
`link_directories( $ENV{LD_LIBRARY_PATH} )`
Since LD_LIBRARY_PATH is a colon separated list of paths, and this seems to generate 
`-L/path1:/path2`
 which is not valid, at least with g++.

**Comment by schmeing** [comment]
Thank you for the feedback and sorry for the late response. Both issues should be fixed now.
